# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # plaintext fixers
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix, lf]
      # config syntax checkers
      - id: check-yaml
      - id: check-json
      - id: check-toml
      # filesystems checkers
      - id: check-symlinks
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      # check git messages
      - id: gitlint
  - repo: https://github.com/bwbaugh/haskell-pre-commit-hooks
    rev: v0.2.1
    hooks:
      # Haskell linter
      - id: hlint
  - repo: local
    hooks:
      # Haskell formatter
      - id: fourmolu
        name: fourmolu
        entry: fourmolu --mode=inplace
        language: system
        files: '\.hs$'
