name: mcsp-algorithms
version: 0.0.2
github: Problemas-de-Particao-de-Strings/MCSP-Algorithms
license: MIT
author:
  - Leonardo Rodrigues <leonardosrodrigues1@gmail.com>
  - Tiago de Paula <tiagodepalves@gmail.com>
copyright:
  - (c) 2023 Leonardo de Sousa Rodrigues
  - (c) 2023 Tiago de Paula Alves

extra-source-files:
  - README.md

# Metadata used when publishing your package
synopsis: Algorithms for Minimum Common String Partition (MCSP) in Haskell.
category: College,MCSP,Algorithms,String,Partition

# To avoid duplicated efforts in documentation and dealing with the complications of embedding
# Haddock markup inside cabal files, it is common to point users to the README.md file.
description: |
  Please see the README on GitHub at
  <https://github.com/Problemas-de-Particao-de-Strings/MCSP-Algorithms#readme>.

# Using modern Haskell features
language: GHC2021
default-extensions:
  - DerivingStrategies
  - NoImplicitPrelude
  - OverloadedLists
  - OverloadedStrings
  - PatternSynonyms
  - TemplateHaskell
  - TypeFamilies
  - ViewPatterns

library:
  source-dirs: src
  exposed-modules:
    - MCSP.Data.RadixTree
    - MCSP.Data.String
    - MCSP.Data.String.TH
    - MCSP.Data.String.Extra
    - MCSP.Heuristics

dependencies:
  - base >= 4.18 && < 5
  - containers >= 0.6.7 && < 1
  - extra >= 1.7.14 && < 2
  - store >= 0.7.16 && < 1
  - template-haskell > 2.20 && < 3
  - vector >= 0.13 && < 1
  - vector-th-unbox >= 0.2.2 && < 1

internal-libraries:
  mcsp-test-lib:
    source-dirs: test/lib
    exposed-modules:
      - MCSP.System.Random
      - MCSP.System.Random.TH
      - MCSP.TestLib.Heuristics
      - MCSP.TestLib.Random
      - MCSP.TestLib.Sample
    dependencies:
      - mcsp-algorithms
      - MonadRandom >= 0.6 && < 1
      - pcg-random >= 0.1.4 && < 1
      - random-shuffle >= 0.0.4 && < 1

executables:
  playground:
    main: Main.hs
    source-dirs: app
    dependencies:
      - mcsp-algorithms
      - mcsp-test-lib
    ghc-options:
      - -threaded
      - -feager-blackholing
      - -rtsopts
      - -with-rtsopts=-N

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - mcsp-algorithms
      - mcsp-test-lib
      # these dependencies are repeated here for Haskell Language Server to work in 'mcsp-test-lib'
      - MonadRandom >= 0.6 && < 1
      - pcg-random >= 0.1.4 && < 1
      - random-shuffle >= 0.0.4 && < 1
    ghc-options:
      - -threaded
      - -feager-blackholing
      - -rtsopts
      - -with-rtsopts=-N

benchmarks:
  bench:
    main: Bench.hs
    source-dirs: bench
    dependencies:
      - mcsp-algorithms
      - mcsp-test-lib
      - criterion >= 1.6.3.0 && < 2
    ghc-options:
      - -threaded
      - -feager-blackholing
      - -rtsopts
      - -with-rtsopts=-N

ghc-options:
  # Optimization flags
  - -O2
  - -fasm-shortcutting
  - -fdicts-strict
  - -fexpose-all-unfoldings
  - -flate-dmd-anal
  - -flate-specialise
  - -fpedantic-bottoms
  - -fregs-iterative
  - -fspecialise-aggressively
  # Additional warnings
  - -Wall
  - -Wcompat
  - -Wderiving-defaults
  - -Widentities
  - -Winaccessible-code
  - -Wincomplete-patterns
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissed-specialisations
  - -Wmissing-deriving-strategies
  - -Wmissing-signatures
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Woverflowed-literals
  - -Wpartial-fields
  - -Wredundant-constraints
