name: playground
version: 0.0.1
github: Problemas-de-Particao-de-Strings/playground
license: MIT
author:
  - Leonardo Rodrigues <leonardosrodrigues1@gmail.com>
  - Tiago de Paula <tiagodepalves@gmail.com>
copyright:
  - (c) 2023 Leonardo de Sousa Rodrigues
  - (c) 2023 Tiago de Paula Alves

extra-source-files:
  - README.md

# Metadata used when publishing your package
synopsis: Discovering Haskell
category: College

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Problemas-de-Particao-de-Strings/playground#readme>

# Using modern Haskell features
language: GHC2021
default-extensions:
  - DerivingStrategies
  - TemplateHaskell

dependencies:
  - base >= 4.14 && < 5
  - pcg-random >= 0.1.4 && < 1
  - random-shuffle >= 0.0.4 && < 1
  - vector >= 0.13 && < 1
  - vector-th-unbox >= 0.2.2 && < 1

ghc-options:
  # Optimization flags
  - -O2
  - -fasm-shortcutting
  - -fdicts-strict
  - -fexpose-all-unfoldings
  - -flate-dmd-anal
  - -flate-specialise
  - -fpedantic-bottoms
  - -fregs-iterative
  # Additional warnings
  - -Wall
  - -Wcompat
  - -Wderiving-defaults
  - -Widentities
  - -Winaccessible-code
  - -Wincomplete-patterns
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissed-specialisations
  - -Wmissing-deriving-strategies
  - -Wmissing-signatures
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Woverflowed-literals
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules: Strings

executables:
  playground-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -feager-blackholing
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - playground

tests:
  playground-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -feager-blackholing
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - playground
