name: mcsp-algorithms
version: 0.1.0
github: Problemas-de-Particao-de-Strings/MCSP-Algorithms
license: MIT
author:
  - Leonardo Rodrigues <leonardosrodrigues1@gmail.com>
  - Tiago de Paula <tiagodepalves@gmail.com>
copyright:
  - (c) 2023 Leonardo de Sousa Rodrigues
  - (c) 2023 Tiago de Paula Alves

extra-source-files:
  - README.md

# Metadata used when publishing your package
synopsis: Algorithms for Minimum Common String Partition (MCSP) in Haskell.
category: College,MCSP,Algorithms,String,Partition

# To avoid duplicated efforts in documentation and dealing with the complications of embedding
# Haddock markup inside cabal files, it is common to point users to the README.md file.
description: |
  Please see the README on GitHub at
  <https://github.com/Problemas-de-Particao-de-Strings/MCSP-Algorithms#readme>.

# Using modern Haskell features
language: GHC2021
default-extensions:
  - DerivingStrategies
  - DerivingVia
  - ImplicitParams
  - NoImplicitPrelude
  - OverloadedLists
  - OverloadedStrings
  - PatternSynonyms
  - QuantifiedConstraints
  - RecordWildCards
  - TemplateHaskell
  - TypeFamilies
  - UndecidableInstances
  - ViewPatterns

library:
  source-dirs: src
  exposed-modules:
    - MCSP.Algorithms.Vector
    - MCSP.Data.MatchingGraph
    - MCSP.Data.Meta
    - MCSP.Data.Pair
    - MCSP.Data.RadixTree
    - MCSP.Data.String
    - MCSP.Data.String.TH
    - MCSP.Data.String.Extra
    - MCSP.Heuristics
    - MCSP.Heuristics.PSOBased
    - MCSP.System.Random
    - MCSP.Text.ReadP

dependencies:
  - base >= 4.18.1 && < 5
  - containers >= 0.6.7 && < 1
  - data-interval >= 2.1.1 && < 3
  - deepseq >= 1.4.8.1 && < 2
  - extra >= 1.7.14 && < 2
  - pcg-random >= 0.1.4 && < 1
  - random-shuffle >= 0.0.4 && < 1
  - safe >= 0.3.19 && < 1
  - template-haskell >= 2.20 && < 3
  - transformers >= 0.6.1 && < 1
  - type-map >= 0.1.7.0 && < 1
  - vector >= 0.13.1 && < 1
  - vector-algorithms >= 0.9.0.1 && < 1
  - vector-th-unbox >= 0.2.2 && < 1

executables:
  playground:
    main: Main.hs
    source-dirs: app
    dependencies:
      - mcsp-algorithms
      - mcsp-test-lib
    ghc-options: &binary-ghc-options
      - -threaded
      - -feager-blackholing
      - -rtsopts
      - -with-rtsopts=-N

internal-libraries:
  mcsp-test-lib:
    source-dirs: test/lib
    exposed-modules:
      - MCSP.System.Path
      - MCSP.System.Path.TH
      - MCSP.System.Repl
      - MCSP.System.Statistics
      - MCSP.System.TimeIt
      - MCSP.TestLib.Heuristics
      - MCSP.TestLib.Heuristics.Safe
      - MCSP.TestLib.Heuristics.TH
      - MCSP.TestLib.Random
      - MCSP.TestLib.Sample
    dependencies:
      - mcsp-algorithms
      - directory >= 1.3.8.1 && < 2
      - filepath >= 1.4.100.4 && < 2
      - process >= 1.6.17 && < 2
      - statistics >= 0.16.2.1 && < 1
      - time >= 1.12.2 && < 2

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - mcsp-algorithms
      - mcsp-test-lib
      - doctest >= 0.22.2 && < 1
      - extended-reals >= 0.2.4.0 && < 1
      - tasty >= 1.5 && < 2
      - tasty-quickcheck >= 0.10.3 && < 1
      # these dependencies are repeated here for Haskell Language Server to work in 'mcsp-test-lib'
      - directory >= 1.3.8.1 && < 2
      - filepath >= 1.4.100.4 && < 2
      - process >= 1.6.17 && < 2
      - statistics >= 0.16.2.1 && < 1
      - time >= 1.12.2 && < 2
    ghc-options: *binary-ghc-options

benchmarks:
  blocks:
    main: Bench.hs
    source-dirs: bench/blocks
    dependencies:
      - mcsp-algorithms
      - mcsp-test-lib
      - mwc-random >= 0.15.0.2 && < 1
      - statistics >= 0.16.2.1 && < 1
      - time >= 1.12.2 && < 2
    ghc-options: *binary-ghc-options
  time:
    main: Bench.hs
    source-dirs: bench/time
    dependencies:
      - mcsp-algorithms
      - mcsp-test-lib
      - criterion >= 1.6.3.0 && < 2
    ghc-options: *binary-ghc-options

ghc-options:
  # Optimization flags
  - -O2
  - -fasm-shortcutting
  - -fdicts-strict
  - -fexpose-all-unfoldings
  - -flate-dmd-anal
  - -flate-specialise
  - -fpedantic-bottoms
  - -fregs-iterative
  - -fspecialise-aggressively
  # Additional warnings
  - -Wall
  - -Wcompat
  - -Wderiving-defaults
  - -Widentities
  - -Winaccessible-code
  - -Wincomplete-patterns
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissed-specialisations
  - -Wmissing-deriving-strategies
  - -Wmissing-signatures
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Woverflowed-literals
  - -Wpartial-fields
  - -Wredundant-constraints
